// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Partner.GRPC.Data;

#nullable disable

namespace Partner.GRPC.Migrations
{
    [DbContext(typeof(PartnerContext))]
    partial class PartnerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Partner.GRPC.Models.Lab", b =>
                {
                    b.Property<Guid>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Zip")
                        .HasColumnType("INTEGER");

                    b.HasKey("LabId");

                    b.ToTable("Labs");

                    b.HasData(
                        new
                        {
                            LabId = new Guid("03755f35-35b6-4674-8f3d-9d69eb3acad6"),
                            Address = "",
                            City = "Miami",
                            Country = "",
                            Email = "",
                            LabName = "LAB ONE",
                            LabType = "Specimen",
                            Manager = "",
                            Phone = "999-888-3333",
                            State = "FL",
                            TaxCode = 999999,
                            Website = "",
                            Zip = 33154
                        },
                        new
                        {
                            LabId = new Guid("aabcad5d-c2ad-4502-b71b-b6ec0e5bcf85"),
                            Address = "",
                            City = "Phoenix",
                            Country = "",
                            Email = "",
                            LabName = "LAB TWO",
                            LabType = "Blood",
                            Manager = "",
                            Phone = "444-222-7777",
                            State = "AZ",
                            TaxCode = 888888,
                            Website = "",
                            Zip = 85132
                        });
                });

            modelBuilder.Entity("Partner.GRPC.Models.Shipper", b =>
                {
                    b.Property<Guid>("ShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipperName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShipperId");

                    b.ToTable("Shippers");

                    b.HasData(
                        new
                        {
                            ShipperId = new Guid("3eb4adf2-df2a-499c-8010-e980f8b71d97"),
                            ShipperName = "FedEx",
                            TrackingLink = "www.fedex.com/tracking/"
                        },
                        new
                        {
                            ShipperId = new Guid("32aa8e59-0d18-4292-beac-a56edfecb170"),
                            ShipperName = "USPS",
                            TrackingLink = "www.usps.com/tracking/"
                        },
                        new
                        {
                            ShipperId = new Guid("27a1c178-2b83-42b8-86d8-5b1659848ecd"),
                            ShipperName = "UPS",
                            TrackingLink = "www.ups.com/tracking/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
