version: '3.4'

services:
  providerdb:
    container_name: providerdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ProviderDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_provider:/var/lib/postgresql/data/

  workorderdb:
    container_name: workorderdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=WorkOrderDB
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_workorder:/var/lib/postgresql/data/

  requestorderdb:
    container_name: requestorderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=qweQWE123!@#
    restart: always
    ports:
      - "1533:1433"

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  provider.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=providerdb;Port=5432;Database=ProviderDB;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - providerdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  workorder.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=workorderdb;Port=5432;Database=WorkOrderDB;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__LabUrl=https://partner.grpc:8081
      - GrpcSettings__ShipperUrl=https://partner.grpc:8081
    depends_on:
      - workorderdb
      - distributedcache
      - partner.grpc

    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  partner.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=PartnerDB;
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
