version: '3.4'

services:
  providerdb:
    image: postgres

  workorderdb:
    image: postgres

  distributedcache:
    image: redis

  requestorderdb:
    image: mcr.microsoft.com/mssql/server

  provider.api:
    image: ${DOCKER_REGISTRY-}providerapi
    build:
      context: .
      dockerfile: Services/Provider/Provider.API/Dockerfile

  workorder.api:
    image: ${DOCKER_REGISTRY-}workorderapi
    build:
      context: .
      dockerfile: Services/WorkOrder/WorkOrder.API/Dockerfile

  partner.grpc:
    image: ${DOCKER_REGISTRY-}partnergrpc
    build:
      context: .
      dockerfile: Services/Partner/Partner.GRPC/Dockerfile

volumes:
  postgres_provider:
  postgres_workorder:  

