version: '3.4'

services:
  providerdb:
    image: postgres

  provider.api:
    image: ${DOCKER_REGISTRY-}providerapi
    build:
      context: .
      dockerfile: Services/Provider/Provider.API/Dockerfile

volumes:
  postgres_provider: