version: '3.4'

services:
  providerdb:
    container_name: providerdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ProviderDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_provider:/var/lib/postgresql/data/

# services:
#   provider.api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=8080
#       - ASPNETCORE_HTTPS_PORTS=8081
#     ports:
#       - "8080"
#       - "8081"
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#       - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro