global using ApplicationBlocks.CQRS;
global using FluentValidation;
global using HealthCareProvider.API.Domain;
global using HealthCareProvider.API.DTOs;
global using Carter;
global using Mapster;
global using Marten;
global using Marten.Pagination;
global using MediatR;
